// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team620.robot;
    
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.RobotDrive.MotorType;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainmotorFRTalon;
    public static CANTalon driveTrainmotorFLTalon; // backwards
    public static CANTalon driveTrainmotorRRTalon;
    public static CANTalon driveTrainmotorRLTalon; // backwards
    public static Jaguar driveTrainmotorFR;
    public static Jaguar driveTrainmotorFL;
    public static Jaguar driveTrainmotorRR;
    public static Jaguar driveTrainmotorRL;

    public static RobotDrive driveTrainRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
    	//Order on all robots is: Rear Left = 1, Front Left = 2, Front Right = 3, Rear Right = 4
    	
        driveTrainmotorRL = new Jaguar(1);
        driveTrainmotorFL = new Jaguar(2);
        driveTrainmotorFR = new Jaguar(3);
        driveTrainmotorRR = new Jaguar(4);
        if(driveTrainmotorRL == null)
        {
        	SmartDashboard.putString("DB/String0", "CANTalon = true");
        	 driveTrainmotorRLTalon = new CANTalon(1);
             //driveTrainmotorRLTalon.reverseOutput(true);
             
             //LiveWindow.addActuator("DriveTrain", "motorRL", (LiveWindowSendable) driveTrainmotorRL);

             driveTrainmotorFLTalon = new CANTalon(2);
             	//driveTrainmotorFLTalon.reverseOutput(true);
             //LiveWindow.addActuator("DriveTrain", "motorFL", (LiveWindowSendable) driveTrainmotorFL);
             
             driveTrainmotorFRTalon = new CANTalon(3);
             //LiveWindow.addActuator("DriveTrain", "motorFR", (LiveWindowSendable) driveTrainmotorFR);
             
             driveTrainmotorRRTalon = new CANTalon(4);
             //LiveWindow.addActuator("DriveTrain", "motorRR", (LiveWindowSendable) driveTrainmotorRR);
             
             driveTrainRobotDrive41 = new RobotDrive(
            		 driveTrainmotorFLTalon, 
            		 driveTrainmotorRLTalon,
                     driveTrainmotorFRTalon, 
                     driveTrainmotorRRTalon);
        }
        else
        {
        	SmartDashboard.putString("DB/String0", "Jaguar = true");
        	
            driveTrainRobotDrive41 = new RobotDrive(
            		driveTrainmotorFL, 
            		driveTrainmotorRL,
                    driveTrainmotorFR, 
                    driveTrainmotorRR);
        }
        driveTrainRobotDrive41.setInvertedMotor(MotorType.kRearLeft, true);
        driveTrainRobotDrive41.setInvertedMotor(MotorType.kFrontLeft, true);

        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
  