// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team620.robot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainmotorFR;
    public static CANTalon driveTrainmotorFL; // backwards
    public static CANTalon driveTrainmotorRR;
    public static CANTalon driveTrainmotorRL; // backwards
    public static RobotDrive driveTrainRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainmotorFR = new CANTalon(3);
	//LiveWindow.addActuator("DriveTrain", "motorFR", (CANTalon) driveTrainmotorFR);
        
        driveTrainmotorFL = new CANTalon(2);
        driveTrainmotorFL.reverseOutput(true);
	//LiveWindow.addActuator("DriveTrain", "motorFL", (CANTalon) driveTrainmotorFL);
        
        driveTrainmotorRR = new CANTalon(4);
	//LiveWindow.addActuator("DriveTrain", "motorRR", (CANTalon) driveTrainmotorRR);
        
        driveTrainmotorRL = new CANTalon(1);
        driveTrainmotorFL.reverseOutput(true);
	//LiveWindow.addActuator("DriveTrain", "motorRL", (CANTalon) driveTrainmotorRL);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainmotorRL, driveTrainmotorFL,
              driveTrainmotorFR, driveTrainmotorRR);
	
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
  